export const companies = [
	{
		id: 1,
		title: 'Jabbersphere',
		address: '3997 Myrtle Circle',
	},
	{
		id: 2,
		title: 'Yodel',
		address: '4306 Green Ridge Alley',
	},
	{
		id: 3,
		title: 'Wordpedia',
		address: '1 Farragut Alley',
	},
	{
		id: 4,
		title: 'Babbleblab',
		address: '44133 Namekagon Point',
	},
	{
		id: 5,
		title: 'Zooxo',
		address: '10 Oak Valley Center',
	},
]

export const staff = [
	{
		id: 1,
		companyId: 2,
		firstName: 'Claudianus',
		lastName: 'Keaysell',
		jobTitle: 'Staff Accountant IV',
	},
	{
		id: 2,
		companyId: 3,
		firstName: 'Bentley',
		lastName: 'Cuskery',
		jobTitle: 'Civil Engineer',
	},
	{
		id: 3,
		companyId: 5,
		firstName: 'Gerhard',
		lastName: 'Polkinhorn',
		jobTitle: 'Executive Secretary',
	},
	{
		id: 4,
		companyId: 2,
		firstName: 'Angelo',
		lastName: 'Gearing',
		jobTitle: 'Social Worker',
	},
	{
		id: 5,
		companyId: 3,
		firstName: 'Jilli',
		lastName: 'Myall',
		jobTitle: 'Office Assistant I',
	},
	{
		id: 6,
		companyId: 3,
		firstName: 'Dorian',
		lastName: "O'Dennehy",
		jobTitle: 'Professor',
	},
	{
		id: 7,
		companyId: 1,
		firstName: 'Claresta',
		lastName: 'Ateridge',
		jobTitle: 'Help Desk Technician',
	},
	{
		id: 8,
		companyId: 5,
		firstName: 'Sibyl',
		lastName: 'Linkleter',
		jobTitle: 'Statistician IV',
	},
	{
		id: 9,
		companyId: 5,
		firstName: 'Isabella',
		lastName: 'Paulillo',
		jobTitle: 'VP Product Management',
	},
	{
		id: 10,
		companyId: 4,
		firstName: 'Sergent',
		lastName: 'Penhall',
		jobTitle: 'VP Sales',
	},
	{
		id: 11,
		companyId: 5,
		firstName: 'Edvard',
		lastName: 'Vitet',
		jobTitle: 'Systems Administrator IV',
	},
	{
		id: 12,
		companyId: 1,
		firstName: 'Joanne',
		lastName: 'Hobell',
		jobTitle: 'Systems Administrator I',
	},
	{
		id: 13,
		companyId: 3,
		firstName: 'Abigale',
		lastName: 'Merigon',
		jobTitle: 'Senior Cost Accountant',
	},
	{
		id: 14,
		companyId: 4,
		firstName: 'Florette',
		lastName: 'Eversfield',
		jobTitle: 'Product Engineer',
	},
	{
		id: 15,
		companyId: 5,
		firstName: 'Rowney',
		lastName: 'Orsi',
		jobTitle: 'Compensation Analyst',
	},
	{
		id: 16,
		companyId: 4,
		firstName: 'Roseanne',
		lastName: 'Vannet',
		jobTitle: 'Senior Cost Accountant',
	},
	{
		id: 17,
		companyId: 2,
		firstName: 'Odelia',
		lastName: 'Penright',
		jobTitle: 'Account Representative IV',
	},
	{
		id: 18,
		companyId: 4,
		firstName: 'Estrellita',
		lastName: 'Davidovitz',
		jobTitle: 'Media Manager II',
	},
	{
		id: 19,
		companyId: 3,
		firstName: 'Mead',
		lastName: 'Bracken',
		jobTitle: 'Recruiter',
	},
	{
		id: 20,
		companyId: 1,
		firstName: 'Ash',
		lastName: 'Pighills',
		jobTitle: 'Recruiting Manager',
	},
]
